name: 'Save Cache with GCS Support'
description: 'Save cache artifacts to Google Cloud Storage or GitHub with automatic fallback'
author: 'danySam'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
  upload-chunk-size:
    description: 'The chunk size used to split up large files during upload, in bytes'
    required: false
  enableCrossOsArchive:
    description: 'An optional boolean when enabled, allows windows runners to save caches that can be restored on other platforms'
    default: 'false'
    required: false
  gcs-bucket:
    description: 'Google Cloud Storage bucket name to use for caching. When provided, GCS will be used as the cache backend.'
    required: false
  gcs-path-prefix:
    description: 'Optional prefix path within the GCS bucket for cache files'
    default: 'github-cache'
    required: false
runs:
  using: 'node20'
  main: '../dist/save-only/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
